# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_UI(object):
    def setupUi(self, UI):
        UI.setObjectName("UI")
        UI.setEnabled(True)
        UI.resize(1100, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(UI.sizePolicy().hasHeightForWidth())
        UI.setSizePolicy(sizePolicy)
        UI.setMinimumSize(QtCore.QSize(1100, 800))
        UI.setMaximumSize(QtCore.QSize(1100, 800))
        UI.setStyleSheet("QWidget#UI {\n"
"background-color: rgb(255, 255, 255);\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(UI)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_bar = QtWidgets.QFrame(UI)
        self.frame_bar.setStyleSheet("QFrame{\n"
"    \n"
"    background-color: rgb(85, 85, 127);\n"
"border-top-left-radius:10px;\n"
"border-top-right-radius:10px;\n"
"border-bottom-right-radius:0px;\n"
"border-bottom-left-radius:0px;\n"
"}")
        self.frame_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_bar.setObjectName("frame_bar")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_bar)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.Label_time = QtWidgets.QLabel(self.frame_bar)
        self.Label_time.setStyleSheet("QLabel#Label_time{\n"
"    font: 9pt \"Lucida Handwriting\";\n"
"}")
        self.Label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_time.setObjectName("Label_time")
        self.horizontalLayout_4.addWidget(self.Label_time)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.Button_delete = QtWidgets.QPushButton(self.frame_bar)
        self.Button_delete.setMinimumSize(QtCore.QSize(33, 29))
        self.Button_delete.setStyleSheet("QToolButton{\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"    border:0px solid rgb(25, 87, 16);\n"
"    border-radius:23px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 0, 0, 15);\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0, 0, 0, 20);\n"
"\n"
"}")
        self.Button_delete.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/关闭.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/关闭 (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Button_delete.setIcon(icon)
        self.Button_delete.setObjectName("Button_delete")
        self.horizontalLayout_4.addWidget(self.Button_delete)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 100)
        self.verticalLayout.addWidget(self.frame_bar)
        self.frame_main = QtWidgets.QFrame(UI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_main.sizePolicy().hasHeightForWidth())
        self.frame_main.setSizePolicy(sizePolicy)
        self.frame_main.setStyleSheet("QFrame#frame_2{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}")
        self.frame_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_main)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout1.setSpacing(0)
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.Frame_changeForm = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame_changeForm.sizePolicy().hasHeightForWidth())
        self.Frame_changeForm.setSizePolicy(sizePolicy)
        self.Frame_changeForm.setStyleSheet("QFrame#Frame_changeForm{ \n"
"    \n"
"    background-color: rgb(85, 85, 127);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:0px;\n"
"    border-bottom-left-radius:10px;\n"
"}")
        self.Frame_changeForm.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_changeForm.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_changeForm.setObjectName("Frame_changeForm")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Frame_changeForm)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 400)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.Frame_changeForm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(106, 180))
        self.listWidget.setStyleSheet("QListWidget {\n"
"    border: 10px solid;\n"
"    \n"
"    background-color: rgb(85, 85, 255);\n"
"    \n"
"    font: 12pt \"Lucida Handwriting\";\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0.091, x2:0, y2:1, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.017, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"}\n"
"QListView::item{\n"
"    background-color: transparent;\n"
"    padding:9px;\n"
"}\n"
"QListView::item:hover {\n"
"    background-color: rgb(230, 230, 230);\n"
"}\n"
"QListView::item:selected {\n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(218, 218, 218);\n"
"}")
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/page.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setIcon(icon1)
        self.listWidget.addItem(item)
        self.verticalLayout_2.addWidget(self.listWidget)
        self.horizontalLayout1.addWidget(self.Frame_changeForm)
        self.Frame_Form = QtWidgets.QFrame(self.frame_main)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(8)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Frame_Form.sizePolicy().hasHeightForWidth())
        self.Frame_Form.setSizePolicy(sizePolicy)
        self.Frame_Form.setStyleSheet("QFrame#Frame_Form { \n"
"    background-color: rgb(135, 171, 255);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:10px;\n"
"    border-bottom-left-radius:0px;\n"
"}")
        self.Frame_Form.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame_Form.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame_Form.setObjectName("Frame_Form")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Frame_Form)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.StackedMainWidget = QtWidgets.QStackedWidget(self.Frame_Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StackedMainWidget.sizePolicy().hasHeightForWidth())
        self.StackedMainWidget.setSizePolicy(sizePolicy)
        self.StackedMainWidget.setStyleSheet("QStackedWidget#stackedWidget{ \n"
"\n"
"}\n"
"QWidget#page_1{ \n"
"    \n"
"    background-color: rgb(85, 85, 127);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"QWidget#page_2{ \n"
"    background-color: rgb(85, 85, 127);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"QWidget#page_3{ \n"
"    background-color: rgb(85, 85, 127);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}\n"
"QWidget#page_4{ \n"
"    background-color: rgb(85, 85, 127);\n"
"    border-top-left-radius:0px;\n"
"    border-top-right-radius:0px;\n"
"    border-bottom-right-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"}")
        self.StackedMainWidget.setObjectName("StackedMainWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setStyleSheet("QLabel{\n"
"    font: 20px \"楷体\";\n"
"}\n"
"\n"
"QPushButton {\n"
"    font:  \"楷体\";\n"
"}")
        self.page_1.setObjectName("page_1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.page_1)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll_Page1 = QtWidgets.QWidget()
        self.scroll_Page1.setGeometry(QtCore.QRect(0, 0, 955, 890))
        self.scroll_Page1.setStyleSheet("QWidget#scroll_Page1 {\n"
"    \n"
"    background-color: rgb(85, 85, 127);\n"
"    border: 10px solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0.091, x2:0, y2:1, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.017, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.scroll_Page1.setObjectName("scroll_Page1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scroll_Page1)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame1 = QtWidgets.QFrame(self.scroll_Page1)
        self.frame1.setMinimumSize(QtCore.QSize(600, 500))
        self.frame1.setStyleSheet("QFrame#frame1{\n"
"background-color: transparent;\n"
"border-radius: 10px;\n"
"}")
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.frame1)
        self.frame.setStyleSheet("QFrame#frame{\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setStyleSheet("QFrame#frame_3{\n"
"    border: 10px solid;\n"
"    \n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    \n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.017, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.091, x2:0, y2:1, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem4, 1, 2, 1, 1)
        self.Label_camera = QtWidgets.QLabel(self.frame_3)
        self.Label_camera.setStyleSheet("QLabel#Label_camera{\n"
"    background-color: rgb(218, 218, 218);\n"
"    border-top-left-radius:5px;\n"
"    border-top-right-radius:5px;\n"
"    border-bottom-right-radius:5px;\n"
"    border-bottom-left-radius:5px;\n"
"}")
        self.Label_camera.setText("")
        self.Label_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.Label_camera.setObjectName("Label_camera")
        self.gridLayout.addWidget(self.Label_camera, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem5, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 12)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 12)
        self.gridLayout.setRowStretch(2, 1)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setStyleSheet("QFrame#frame_4{\n"
"    border: 10px solid;\n"
"    \n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    \n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.017, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.091, x2:0, y2:1, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_4)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.Button_camera = QtWidgets.QToolButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_camera.sizePolicy().hasHeightForWidth())
        self.Button_camera.setSizePolicy(sizePolicy)
        self.Button_camera.setStyleSheet("QToolButton{\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"border:0px solid rgb(25, 87, 16);\n"
"    border-radius:23px;\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"background-color: rgba(0, 0, 0, 15);\n"
"\n"
"}\n"
"QToolButton:pressed {\n"
"background-color: rgba(0, 0, 0, 20);\n"
"\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/Camera2.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Button_camera.setIcon(icon2)
        self.Button_camera.setIconSize(QtCore.QSize(28, 28))
        self.Button_camera.setObjectName("Button_camera")
        self.horizontalLayout_7.addWidget(self.Button_camera)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.Button_piccap = QtWidgets.QToolButton(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_piccap.sizePolicy().hasHeightForWidth())
        self.Button_piccap.setSizePolicy(sizePolicy)
        self.Button_piccap.setStyleSheet("QToolButton{\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"border:0px solid rgb(25, 87, 16);\n"
"    border-radius:23px;\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"background-color: rgba(0, 0, 0, 15);\n"
"\n"
"}\n"
"QToolButton:pressed {\n"
"background-color: rgba(0, 0, 0, 20);\n"
"\n"
"}")
        self.Button_piccap.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/picture.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/picture.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/picture.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/picture.svg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon3.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/picture.svg"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        self.Button_piccap.setIcon(icon3)
        self.Button_piccap.setIconSize(QtCore.QSize(28, 28))
        self.Button_piccap.setObjectName("Button_piccap")
        self.horizontalLayout_7.addWidget(self.Button_piccap)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem8)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_7.setStretch(3, 1)
        self.horizontalLayout_7.setStretch(4, 1)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.verticalLayout_6.setStretch(0, 10)
        self.verticalLayout_6.setStretch(1, 2)
        self.horizontalLayout_5.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.frame1)
        self.frame_2.setStyleSheet("QFrame#frame_2{\n"
"    background-color: transparent;\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_7.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setStyleSheet("QFrame#frame_7{\n"
"    border: 10px solid;\n"
"    \n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    \n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.017, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.091, x2:0, y2:1, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        self.label_4.setStyleSheet("QLabel {\n"
"    /* 背景颜色 */\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    \n"
"    /* 边框 */\n"
"    border: 2px solid #cccccc; /* 灰色边框，宽度2px */\n"
"    border-radius: 8px;        /* 圆角边框，半径8px */\n"
"    \n"
"    /* 字体 */\n"
"    font-size: 16px;           /* 字体大小 */\n"
"    font-family: \"Arial\";      /* 字体类型 */\n"
"    color: #333333;            /* 文字颜色 */\n"
"    \n"
"    /* 内边距 */\n"
"    padding: 5px;              /* 控件内的填充距离 */\n"
"    \n"
"    /* 文本对齐 */\n"
"    text-align: center;        /* 文本居中对齐 */\n"
"    \n"
"    /* 阴影效果 */\n"
"    /* 注意：Qt 5.11 之后增加了对 CSS3 box-shadow 属性的支持 */\n"
"    /* 对于较老的Qt版本，可能需要使用自定义绘制 */\n"
"    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1); /* 水平偏移、垂直偏移、模糊半径、颜色 */\n"
"    \n"
"    /* 最小尺寸 */\n"
"    min-width: 200px;          /* 最小宽度 */\n"
"    min-height: 100px;         /* 最小高度 */\n"
"    \n"
"    /* 其他样式 */\n"
"    selection-background-color: #66afe9; /* 选中文本的背景颜色 */\n"
"    selection-color: black;             /* 选中文本的颜色 */\n"
"}")
        self.label_4.setText("")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_8.addWidget(self.label_4)
        self.verticalLayout_7.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_2)
        self.frame_8.setStyleSheet("QFrame#frame_8{\n"
"border: 10px solid;\n"
"    \n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    \n"
"    \n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.017, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.091, x2:0, y2:1, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.toolButton_hide1 = QtWidgets.QToolButton(self.frame_8)
        self.toolButton_hide1.setStyleSheet("QToolButton{\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"border:0px solid rgb(25, 87, 16);\n"
"    border-radius:23px;\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"background-color: rgba(0, 0, 0, 15);\n"
"\n"
"}\n"
"QToolButton:pressed {\n"
"background-color: rgba(0, 0, 0, 20);\n"
"\n"
"}")
        self.toolButton_hide1.setObjectName("toolButton_hide1")
        self.horizontalLayout_8.addWidget(self.toolButton_hide1)
        self.toolButton_hide2 = QtWidgets.QToolButton(self.frame_8)
        self.toolButton_hide2.setStyleSheet("QToolButton{\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"border:0px solid rgb(25, 87, 16);\n"
"    border-radius:23px;\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"background-color: rgba(0, 0, 0, 15);\n"
"\n"
"}\n"
"QToolButton:pressed {\n"
"background-color: rgba(0, 0, 0, 20);\n"
"\n"
"}")
        self.toolButton_hide2.setObjectName("toolButton_hide2")
        self.horizontalLayout_8.addWidget(self.toolButton_hide2)
        self.toolButton_hide3 = QtWidgets.QToolButton(self.frame_8)
        self.toolButton_hide3.setStyleSheet("QToolButton{\n"
"    background-color: rgba(0, 0, 0, 10);\n"
"border:0px solid rgb(25, 87, 16);\n"
"    border-radius:23px;\n"
"\n"
"}\n"
"QToolButton:hover {\n"
"background-color: rgba(0, 0, 0, 15);\n"
"\n"
"}\n"
"QToolButton:pressed {\n"
"background-color: rgba(0, 0, 0, 20);\n"
"\n"
"}")
        self.toolButton_hide3.setObjectName("toolButton_hide3")
        self.horizontalLayout_8.addWidget(self.toolButton_hide3)
        self.verticalLayout_7.addWidget(self.frame_8)
        self.verticalLayout_7.setStretch(0, 10)
        self.verticalLayout_7.setStretch(1, 2)
        self.horizontalLayout_5.addWidget(self.frame_2)
        self.horizontalLayout_5.setStretch(0, 5)
        self.horizontalLayout_5.setStretch(1, 3)
        self.verticalLayout_3.addWidget(self.frame1)
        self.frame2 = QtWidgets.QFrame(self.scroll_Page1)
        self.frame2.setMinimumSize(QtCore.QSize(0, 390))
        self.frame2.setStyleSheet("QFrame#frame2{\n"
"background-color: transparent;\n"
"border-radius: 10px;\n"
"border: 10px solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0.091, x2:0, y2:1, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.017, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"}")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame2)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.tableWidget = QtWidgets.QTableWidget(self.frame2)
        self.tableWidget.setMouseTracking(True)
        self.tableWidget.setTabletTracking(False)
        self.tableWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"    text-align: center;\n"
"    font: 9pt \"Arial\";\n"
"    color: rgb(15, 15, 15);\n"
"    border-radius:0px;\n"
"    selection-color: rgb(11, 11, 11);\n"
"    selection-background-color:  rgb(235, 235, 235);\n"
"    \n"
"    \n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 93, 155, 255), stop:1 rgba(32, 250, 198, 255));\n"
"\n"
"    border: 20px solid;\n"
"    \n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    color: rgb(142, 255, 251);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.017, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:0.091, x2:0, y2:1, stop:0 rgba(85, 85, 255， 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"\n"
"}\n"
"QTableWidget::section{\n"
"border-radius:10px;\n"
"}\n"
"QTableWidget:item{\n"
"    border-bottom:1px solid rgba(50, 50, 50,20);\n"
"}\n"
"QHeaderView::section{\n"
"\n"
"border:none;\n"
"color: rgb(100, 100, 100);\n"
"border-right:1px solid rgba(50, 50, 50,20);\n"
"}\n"
"QTableWidget:item::hover {\n"
"\n"
"\n"
"}\n"
"QTableWidget:item::focus{\n"
"}\n"
"QTableWidget:!enabled\n"
"{\n"
"    background-color: rgb(85, 85, 127);\n"
"}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(8)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        item.setBackground(QtGui.QColor(218, 218, 218))
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(133)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setDefaultSectionSize(35)
        self.horizontalLayout_9.addWidget(self.tableWidget)
        self.verticalLayout_3.addWidget(self.frame2)
        self.scrollArea.setWidget(self.scroll_Page1)
        self.horizontalLayout_2.addWidget(self.scrollArea)
        self.StackedMainWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setStyleSheet("QLabel{\n"
"    font: 20px \"楷体\";\n"
"}")
        self.page_2.setObjectName("page_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setStyleSheet("QLabel#label_3{\n"
"\n"
"\n"
"}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.frame_6 = QtWidgets.QFrame(self.page_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_pic1 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pic1.sizePolicy().hasHeightForWidth())
        self.label_pic1.setSizePolicy(sizePolicy)
        self.label_pic1.setStyleSheet("QLabel {\n"
"    /* 背景颜色 */\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    \n"
"    /* 边框 */\n"
"    border: 2px solid #cccccc; /* 灰色边框，宽度2px */\n"
"    border-radius: 8px;        /* 圆角边框，半径8px */\n"
"    \n"
"    /* 字体 */\n"
"    font-size: 16px;           /* 字体大小 */\n"
"    font-family: \"Arial\";      /* 字体类型 */\n"
"    color: #333333;            /* 文字颜色 */\n"
"    \n"
"    /* 内边距 */\n"
"    padding: 5px;              /* 控件内的填充距离 */\n"
"    \n"
"    /* 文本对齐 */\n"
"    text-align: center;        /* 文本居中对齐 */\n"
"    \n"
"    /* 阴影效果 */\n"
"    /* 注意：Qt 5.11 之后增加了对 CSS3 box-shadow 属性的支持 */\n"
"    /* 对于较老的Qt版本，可能需要使用自定义绘制 */\n"
"    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1); /* 水平偏移、垂直偏移、模糊半径、颜色 */\n"
"    \n"
"    /* 最小尺寸 */\n"
"    min-width: 200px;          /* 最小宽度 */\n"
"    min-height: 100px;         /* 最小高度 */\n"
"    \n"
"    /* 其他样式 */\n"
"    selection-background-color: #66afe9; /* 选中文本的背景颜色 */\n"
"    selection-color: black;             /* 选中文本的颜色 */\n"
"}")
        self.label_pic1.setText("")
        self.label_pic1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic1.setObjectName("label_pic1")
        self.gridLayout_5.addWidget(self.label_pic1, 0, 0, 1, 1)
        self.label_pic2 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pic2.sizePolicy().hasHeightForWidth())
        self.label_pic2.setSizePolicy(sizePolicy)
        self.label_pic2.setStyleSheet("QLabel {\n"
"    /* 背景颜色 */\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    \n"
"    /* 边框 */\n"
"    border: 2px solid #cccccc; /* 灰色边框，宽度2px */\n"
"    border-radius: 8px;        /* 圆角边框，半径8px */\n"
"    \n"
"    /* 字体 */\n"
"    font-size: 16px;           /* 字体大小 */\n"
"    font-family: \"Arial\";      /* 字体类型 */\n"
"    color: #333333;            /* 文字颜色 */\n"
"    \n"
"    /* 内边距 */\n"
"    padding: 5px;              /* 控件内的填充距离 */\n"
"    \n"
"    /* 文本对齐 */\n"
"    text-align: center;        /* 文本居中对齐 */\n"
"    \n"
"    /* 阴影效果 */\n"
"    /* 注意：Qt 5.11 之后增加了对 CSS3 box-shadow 属性的支持 */\n"
"    /* 对于较老的Qt版本，可能需要使用自定义绘制 */\n"
"    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1); /* 水平偏移、垂直偏移、模糊半径、颜色 */\n"
"    \n"
"    /* 最小尺寸 */\n"
"    min-width: 200px;          /* 最小宽度 */\n"
"    min-height: 100px;         /* 最小高度 */\n"
"    \n"
"    /* 其他样式 */\n"
"    selection-background-color: #66afe9; /* 选中文本的背景颜色 */\n"
"    selection-color: black;             /* 选中文本的颜色 */\n"
"}")
        self.label_pic2.setText("")
        self.label_pic2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic2.setObjectName("label_pic2")
        self.gridLayout_5.addWidget(self.label_pic2, 0, 1, 1, 1)
        self.label_pic3 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pic3.sizePolicy().hasHeightForWidth())
        self.label_pic3.setSizePolicy(sizePolicy)
        self.label_pic3.setStyleSheet("QLabel {\n"
"    /* 背景颜色 */\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    \n"
"    /* 边框 */\n"
"    border: 2px solid #cccccc; /* 灰色边框，宽度2px */\n"
"    border-radius: 8px;        /* 圆角边框，半径8px */\n"
"    \n"
"    /* 字体 */\n"
"    font-size: 16px;           /* 字体大小 */\n"
"    font-family: \"Arial\";      /* 字体类型 */\n"
"    color: #333333;            /* 文字颜色 */\n"
"    \n"
"    /* 内边距 */\n"
"    padding: 5px;              /* 控件内的填充距离 */\n"
"    \n"
"    /* 文本对齐 */\n"
"    text-align: center;        /* 文本居中对齐 */\n"
"    \n"
"    /* 阴影效果 */\n"
"    /* 注意：Qt 5.11 之后增加了对 CSS3 box-shadow 属性的支持 */\n"
"    /* 对于较老的Qt版本，可能需要使用自定义绘制 */\n"
"    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1); /* 水平偏移、垂直偏移、模糊半径、颜色 */\n"
"    \n"
"    /* 最小尺寸 */\n"
"    min-width: 200px;          /* 最小宽度 */\n"
"    min-height: 100px;         /* 最小高度 */\n"
"    \n"
"    /* 其他样式 */\n"
"    selection-background-color: #66afe9; /* 选中文本的背景颜色 */\n"
"    selection-color: black;             /* 选中文本的颜色 */\n"
"}")
        self.label_pic3.setText("")
        self.label_pic3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic3.setObjectName("label_pic3")
        self.gridLayout_5.addWidget(self.label_pic3, 1, 0, 1, 1)
        self.label_pic4 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pic4.sizePolicy().hasHeightForWidth())
        self.label_pic4.setSizePolicy(sizePolicy)
        self.label_pic4.setStyleSheet("QLabel {\n"
"    /* 背景颜色 */\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    \n"
"    /* 边框 */\n"
"    border: 2px solid #cccccc; /* 灰色边框，宽度2px */\n"
"    border-radius: 8px;        /* 圆角边框，半径8px */\n"
"    \n"
"    /* 字体 */\n"
"    font-size: 16px;           /* 字体大小 */\n"
"    font-family: \"Arial\";      /* 字体类型 */\n"
"    color: #333333;            /* 文字颜色 */\n"
"    \n"
"    /* 内边距 */\n"
"    padding: 5px;              /* 控件内的填充距离 */\n"
"    \n"
"    /* 文本对齐 */\n"
"    text-align: center;        /* 文本居中对齐 */\n"
"    \n"
"    /* 阴影效果 */\n"
"    /* 注意：Qt 5.11 之后增加了对 CSS3 box-shadow 属性的支持 */\n"
"    /* 对于较老的Qt版本，可能需要使用自定义绘制 */\n"
"    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1); /* 水平偏移、垂直偏移、模糊半径、颜色 */\n"
"    \n"
"    /* 最小尺寸 */\n"
"    min-width: 200px;          /* 最小宽度 */\n"
"    min-height: 100px;         /* 最小高度 */\n"
"    \n"
"    /* 其他样式 */\n"
"    selection-background-color: #66afe9; /* 选中文本的背景颜色 */\n"
"    selection-color: black;             /* 选中文本的颜色 */\n"
"}")
        self.label_pic4.setText("")
        self.label_pic4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pic4.setObjectName("label_pic4")
        self.gridLayout_5.addWidget(self.label_pic4, 1, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_6)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 10)
        self.StackedMainWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setStyleSheet("QLabel{\n"
"    font: 20px \"楷体\";\n"
"}\n"
"QToolButton{\n"
"    font: 20px \"Lucida Handwriting\";\n"
"    \n"
"    background-color: rgb(0, 255, 255);\n"
"    border:0px solid rgb(25, 87, 16);\n"
"    border-radius:23px;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgba(0, 0, 0, 15);\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgba(0, 0, 0, 20);\n"
"\n"
"}")
        self.page_3.setObjectName("page_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.page_3)
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        self.label_2.setMinimumSize(QtCore.QSize(582, 319))
        self.label_2.setMaximumSize(QtCore.QSize(582, 319))
        self.label_2.setStyleSheet("background-image: url(:/image/resouce/image/R-C.png);")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.toolButton_i = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_i.sizePolicy().hasHeightForWidth())
        self.toolButton_i.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/上.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/上 (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_i.setIcon(icon4)
        self.toolButton_i.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_i.setObjectName("toolButton_i")
        self.gridLayout_3.addWidget(self.toolButton_i, 0, 1, 1, 1)
        self.toolButton_j = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_j.sizePolicy().hasHeightForWidth())
        self.toolButton_j.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/右.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/右 (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_j.setIcon(icon5)
        self.toolButton_j.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_j.setObjectName("toolButton_j")
        self.gridLayout_3.addWidget(self.toolButton_j, 1, 0, 1, 1)
        self.toolButton_l = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_l.sizePolicy().hasHeightForWidth())
        self.toolButton_l.setSizePolicy(sizePolicy)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/左.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/左 (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_l.setIcon(icon6)
        self.toolButton_l.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_l.setObjectName("toolButton_l")
        self.gridLayout_3.addWidget(self.toolButton_l, 1, 2, 1, 1)
        self.toolButton_k = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_k.sizePolicy().hasHeightForWidth())
        self.toolButton_k.setSizePolicy(sizePolicy)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/下.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon7.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/下 (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_k.setIcon(icon7)
        self.toolButton_k.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_k.setObjectName("toolButton_k")
        self.gridLayout_3.addWidget(self.toolButton_k, 1, 1, 1, 1)
        self.toolButton_on = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_on.sizePolicy().hasHeightForWidth())
        self.toolButton_on.setSizePolicy(sizePolicy)
        self.toolButton_on.setObjectName("toolButton_on")
        self.gridLayout_3.addWidget(self.toolButton_on, 0, 2, 1, 1)
        self.toolButton_det = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_det.sizePolicy().hasHeightForWidth())
        self.toolButton_det.setSizePolicy(sizePolicy)
        self.toolButton_det.setObjectName("toolButton_det")
        self.gridLayout_3.addWidget(self.toolButton_det, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 3, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem9, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.toolButton_s = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_s.sizePolicy().hasHeightForWidth())
        self.toolButton_s.setSizePolicy(sizePolicy)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/24gl-stopCircle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon8.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/24gl-stopCircle (1).svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_s.setIcon(icon8)
        self.toolButton_s.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_s.setObjectName("toolButton_s")
        self.gridLayout_2.addWidget(self.toolButton_s, 1, 1, 1, 1)
        self.toolButton_x = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_x.sizePolicy().hasHeightForWidth())
        self.toolButton_x.setSizePolicy(sizePolicy)
        self.toolButton_x.setIcon(icon7)
        self.toolButton_x.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_x.setObjectName("toolButton_x")
        self.gridLayout_2.addWidget(self.toolButton_x, 2, 1, 1, 1)
        self.toolButton_a = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_a.sizePolicy().hasHeightForWidth())
        self.toolButton_a.setSizePolicy(sizePolicy)
        self.toolButton_a.setIcon(icon5)
        self.toolButton_a.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_a.setObjectName("toolButton_a")
        self.gridLayout_2.addWidget(self.toolButton_a, 1, 0, 1, 1)
        self.toolButton_d = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_d.sizePolicy().hasHeightForWidth())
        self.toolButton_d.setSizePolicy(sizePolicy)
        self.toolButton_d.setIcon(icon6)
        self.toolButton_d.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_d.setObjectName("toolButton_d")
        self.gridLayout_2.addWidget(self.toolButton_d, 1, 2, 1, 1)
        self.toolButton_w = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_w.sizePolicy().hasHeightForWidth())
        self.toolButton_w.setSizePolicy(sizePolicy)
        self.toolButton_w.setIcon(icon4)
        self.toolButton_w.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_w.setObjectName("toolButton_w")
        self.gridLayout_2.addWidget(self.toolButton_w, 0, 1, 1, 1)
        self.toolButton_q = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_q.sizePolicy().hasHeightForWidth())
        self.toolButton_q.setSizePolicy(sizePolicy)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/左转.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_q.setIcon(icon9)
        self.toolButton_q.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_q.setObjectName("toolButton_q")
        self.gridLayout_2.addWidget(self.toolButton_q, 0, 0, 1, 1)
        self.toolButton_e = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_e.sizePolicy().hasHeightForWidth())
        self.toolButton_e.setSizePolicy(sizePolicy)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/resouce/icon/右转.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_e.setIcon(icon10)
        self.toolButton_e.setIconSize(QtCore.QSize(40, 40))
        self.toolButton_e.setObjectName("toolButton_e")
        self.gridLayout_2.addWidget(self.toolButton_e, 0, 2, 1, 1)
        self.toolButton_yao1 = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_yao1.sizePolicy().hasHeightForWidth())
        self.toolButton_yao1.setSizePolicy(sizePolicy)
        self.toolButton_yao1.setObjectName("toolButton_yao1")
        self.gridLayout_2.addWidget(self.toolButton_yao1, 2, 0, 1, 1)
        self.toolButton_yao2 = QtWidgets.QToolButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_yao2.sizePolicy().hasHeightForWidth())
        self.toolButton_yao2.setSizePolicy(sizePolicy)
        self.toolButton_yao2.setObjectName("toolButton_yao2")
        self.gridLayout_2.addWidget(self.toolButton_yao2, 2, 2, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem10, 0, 4, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem11, 0, 2, 1, 1)
        self.gridLayout_4.setColumnStretch(0, 3)
        self.gridLayout_4.setColumnStretch(1, 9)
        self.gridLayout_4.setColumnStretch(2, 9)
        self.gridLayout_4.setColumnStretch(3, 9)
        self.gridLayout_4.setColumnStretch(4, 3)
        self.verticalLayout_5.addLayout(self.gridLayout_4)
        self.verticalLayout_5.setStretch(0, 10)
        self.verticalLayout_5.setStretch(1, 8)
        self.StackedMainWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setStyleSheet("QLabel{\n"
"    font: 20px \"楷体\";\n"
"}")
        self.page_4.setObjectName("page_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_4)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label = QtWidgets.QLabel(self.page_4)
        self.label.setStyleSheet("QLabel {\n"
"    /* 背景颜色 */\n"
"    background-color: #f0f0f0; /* 浅灰色背景 */\n"
"    \n"
"    /* 边框 */\n"
"    border: 2px solid #cccccc; /* 灰色边框，宽度2px */\n"
"    border-radius: 8px;        /* 圆角边框，半径8px */\n"
"    \n"
"    /* 字体 */\n"
"    font-size: 16px;           /* 字体大小 */\n"
"    font-family: \"Arial\";      /* 字体类型 */\n"
"    color: #333333;            /* 文字颜色 */\n"
"    \n"
"    /* 内边距 */\n"
"    padding: 5px;              /* 控件内的填充距离 */\n"
"    \n"
"    /* 文本对齐 */\n"
"    text-align: center;        /* 文本居中对齐 */\n"
"    \n"
"    /* 阴影效果 */\n"
"    /* 注意：Qt 5.11 之后增加了对 CSS3 box-shadow 属性的支持 */\n"
"    /* 对于较老的Qt版本，可能需要使用自定义绘制 */\n"
"    box-shadow: 2px 2px 4px rgba(0, 0, 0, 0.1); /* 水平偏移、垂直偏移、模糊半径、颜色 */\n"
"    \n"
"    /* 最小尺寸 */\n"
"    min-width: 200px;          /* 最小宽度 */\n"
"    min-height: 100px;         /* 最小高度 */\n"
"    \n"
"    /* 其他样式 */\n"
"    selection-background-color: #66afe9; /* 选中文本的背景颜色 */\n"
"    selection-color: black;             /* 选中文本的颜色 */\n"
"}")
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_6.addWidget(self.label)
        self.StackedMainWidget.addWidget(self.page_4)
        self.horizontalLayout_3.addWidget(self.StackedMainWidget)
        self.horizontalLayout1.addWidget(self.Frame_Form)
        self.horizontalLayout.addLayout(self.horizontalLayout1)
        self.verticalLayout.addWidget(self.frame_main)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 20)

        self.retranslateUi(UI)
        self.StackedMainWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(UI)

    def retranslateUi(self, UI):
        _translate = QtCore.QCoreApplication.translate
        UI.setWindowTitle(_translate("UI", "Form"))
        self.Label_time.setText(_translate("UI", "TextLabel"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("UI", "Page1"))
        item = self.listWidget.item(1)
        item.setText(_translate("UI", "Page2"))
        item = self.listWidget.item(2)
        item.setText(_translate("UI", "Page3"))
        item = self.listWidget.item(3)
        item.setText(_translate("UI", "Page4"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.Button_camera.setText(_translate("UI", "..."))
        self.toolButton_hide1.setText(_translate("UI", "..."))
        self.toolButton_hide2.setText(_translate("UI", "..."))
        self.toolButton_hide3.setText(_translate("UI", "..."))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("UI", "种植作物占比"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("UI", "近期叶片状态统计"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("UI", "环境温湿度数据"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("UI", "土壤温湿度数据"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("UI", "1h"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("UI", "2h"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("UI", "3h"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("UI", "4h"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("UI", "5h"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("UI", "采集检测图片"))
        self.toolButton_i.setText(_translate("UI", "i"))
        self.toolButton_j.setText(_translate("UI", "j"))
        self.toolButton_l.setText(_translate("UI", "l"))
        self.toolButton_k.setText(_translate("UI", "k"))
        self.toolButton_on.setText(_translate("UI", "On"))
        self.toolButton_det.setText(_translate("UI", "Det"))
        self.toolButton_s.setText(_translate("UI", "s"))
        self.toolButton_x.setText(_translate("UI", "x"))
        self.toolButton_a.setText(_translate("UI", "a"))
        self.toolButton_d.setText(_translate("UI", "d"))
        self.toolButton_w.setText(_translate("UI", "w"))
        self.toolButton_q.setText(_translate("UI", "Q"))
        self.toolButton_e.setText(_translate("UI", "E"))
        self.toolButton_yao1.setText(_translate("UI", "1"))
        self.toolButton_yao2.setText(_translate("UI", "2"))
import resource
